using System.Text.Json.Serialization;

namespace Baxy.Core.Operations;

[JsonSourceGenerationOptions(
    PropertyNamingPolicy = JsonKnownNamingPolicy.CamelCase,
    PropertyNameCaseInsensitive = false,
    UnmappedMemberHandling = JsonUnmappedMemberHandling.Disallow,
    GenerationMode = JsonSourceGenerationMode.Default)]
[JsonSerializable(typeof(EmptyArguments))]
[JsonSerializable(typeof(ClipboardReadArguments))]
[JsonSerializable(typeof(ClipboardWriteArguments))]
[JsonSerializable(typeof(ClipboardReadResult))]
[JsonSerializable(typeof(ClipboardWriteOutcome))]
[JsonSerializable(typeof(CreateNoteArguments))]
[JsonSerializable(typeof(NoteSelectorArguments))]
[JsonSerializable(typeof(NoteUpdateArguments))]
[JsonSerializable(typeof(NoteSearchArguments))]
[JsonSerializable(typeof(ListNotesArguments))]
[JsonSerializable(typeof(OpenApplicationArguments))]
[JsonSerializable(typeof(OpenApplicationResult))]
[JsonSerializable(typeof(AudioVolumeArguments))]
[JsonSerializable(typeof(AudioMuteArguments))]
[JsonSerializable(typeof(AudioEndpointStateResult))]
[JsonSerializable(typeof(AudioControlResult))]
[JsonSerializable(typeof(AudioStatusResult))]
[JsonSerializable(typeof(NoteResult))]
[JsonSerializable(typeof(NoteResult[]))]
[JsonSerializable(typeof(NoteSummaryResult))]
[JsonSerializable(typeof(NoteSummaryResult[]))]
[JsonSerializable(typeof(NoteAmbiguityCandidateResult))]
[JsonSerializable(typeof(NoteAmbiguityCandidateResult[]))]
[JsonSerializable(typeof(NoteAmbiguityResult))]
[JsonSerializable(typeof(NoteListResult))]
[JsonSerializable(typeof(TaskCreateArguments))]
[JsonSerializable(typeof(TaskCasArguments))]
[JsonSerializable(typeof(TaskDeleteArguments))]
[JsonSerializable(typeof(TaskUpdateArguments))]
[JsonSerializable(typeof(TaskResolveExactArguments))]
[JsonSerializable(typeof(TaskListArguments))]
[JsonSerializable(typeof(TaskSearchArguments))]
[JsonSerializable(typeof(TaskResult))]
[JsonSerializable(typeof(TaskSummaryResult))]
[JsonSerializable(typeof(TaskSummaryResult[]))]
[JsonSerializable(typeof(TaskSelectionResult))]
[JsonSerializable(typeof(TaskListResult))]
[JsonSerializable(typeof(AppStatusResult))]
[JsonSerializable(typeof(SystemStatusArguments))]
[JsonSerializable(typeof(ProcessListArguments))]
[JsonSerializable(typeof(ProcessListItemResult))]
[JsonSerializable(typeof(ProcessListItemResult[]))]
[JsonSerializable(typeof(ProcessListResult))]
[JsonSerializable(typeof(SystemStatusCpuResult))]
[JsonSerializable(typeof(SystemStatusMemoryResult))]
[JsonSerializable(typeof(SystemStatusDiskResult))]
[JsonSerializable(typeof(SystemStatusBatteryResult))]
[JsonSerializable(typeof(SystemStatusOperatingSystemResult))]
[JsonSerializable(typeof(SystemStatusFailureResult))]
[JsonSerializable(typeof(SystemStatusFailureResult[]))]
[JsonSerializable(typeof(SystemStatusResult))]
internal sealed partial class CoreJsonContext : JsonSerializerContext;
