using Baxy.Providers.Windows.Applications;
using Baxy.Contracts;
using NUnit.Framework;

namespace Baxy.Providers.Windows.Tests;

[TestFixture]
public sealed class WindowsInstalledApplicationOpenProviderTests
{
    private static readonly IReadOnlyList<InstalledApplicationEntry> Catalog =
    [
        new("Steam", @"{7C5A40EF-A0FB-4BFC-874A-C0F2E0B9FA8E}\Steam\steam.exe"),
        new("Steam Support Center", "http://support.steampowered.com/"),
        new("Microsoft Teams", "MSTeams_8wekyb3d8bbwe!MSTeams"),
        new("Spotify", "Microsoft.AutoGenerated.Spotify"),
        new("Paint", "Microsoft.Paint_8wekyb3d8bbwe!App"),
        new("Configuración", "windows.immersivecontrolpanel"),
        new("Asistencia rápida", "MicrosoftCorporationII.QuickAssist_8wekyb3d8bbwe!App"),
        new("Google Chrome", "Chrome"),
        new("Bloc de notas", "Microsoft.WindowsNotepad_8wekyb3d8bbwe!App"),
        new("Visual Studio", "VisualStudio"),
        new("Visual Studio Code", "VisualStudioCode"),
    ];

    [TestCase("steam", "steam", true)]
    [TestCase("steam noticias", "steam", true)]
    [TestCase("list visible steam windows with sizes baxy goal 07", "steam", false)]
    [TestCase("spotify", "steam", false)]
    [TestCase("notepad", "notepad", true)]
    public void WindowTitleDoesNotTreatAnIncidentalMentionAsTheApp(
        string title, string application, bool expected)
    {
        Assert.That(
            WindowsInstalledApplicationPlatform.WindowTitleIdentifiesApplication(
                title,
                application),
            Is.EqualTo(expected));
    }

    [Test]
    public void ExactNameBeatsRelatedStartMenuEntries()
    {
        InstalledApplicationResolution resolution = InstalledApplicationResolver.Resolve(
            "Steam",
            Catalog);

        Assert.Multiple(() =>
        {
            Assert.That(resolution.Entry?.Name, Is.EqualTo("Steam"));
            Assert.That(resolution.Ambiguous, Is.False);
        });
    }

    [Test]
    public void ReservedNotepadIdentityResolvesByWindowsAppIdNotUiLanguage()
    {
        InstalledApplicationResolution resolution = InstalledApplicationResolver.ResolveAppId(
            "Microsoft.WindowsNotepad",
            Catalog);

        Assert.That(resolution.Entry?.AppUserModelId, Does.StartWith("Microsoft.WindowsNotepad"));
    }

    [TestCase("chrome", "Google Chrome")]
    [TestCase("steeam", "Steam")]
    public void SafeUniqueAliasesAndMinorTyposResolve(string query, string expected)
    {
        InstalledApplicationResolution resolution = InstalledApplicationResolver.Resolve(query, Catalog);

        Assert.That(resolution.Entry?.Name, Is.EqualTo(expected));
    }

    [Test]
    public void SimilarStartEntriesRequireAnExactName()
    {
        InstalledApplicationResolution resolution = InstalledApplicationResolver.Resolve(
            "Visual",
            Catalog);

        Assert.Multiple(() =>
        {
            Assert.That(resolution.Entry, Is.Null);
            Assert.That(resolution.Ambiguous, Is.True);
        });
    }

    [TestCase("Spotify", true, "Spotify")]
    [TestCase("Definitely Missing", false, null)]
    public async Task InstalledInventoryChecksCatalogWithoutLaunching(
        string name, bool expectedInstalled, string? expectedDisplayName)
    {
        var platform = new FakePlatform(Catalog);
        var provider = new WindowsInstalledApplicationOpenProvider(platform);

        ApplicationInstalledResult result = await provider.IsInstalledAsync(
            name, CancellationToken.None);

        Assert.Multiple(() =>
        {
            Assert.That(result.Verified, Is.True);
            Assert.That(result.Installed, Is.EqualTo(expectedInstalled));
            Assert.That(result.DisplayName, Is.EqualTo(expectedDisplayName));
            Assert.That(platform.ActivateCalls, Is.Zero);
            Assert.That(platform.FocusCalls, Is.Zero);
        });
    }

    [TestCase("Steam", true, true, "Steam")]
    [TestCase("Visual Studio", true, false, "Visual Studio")]
    [TestCase("Definitely Missing", false, false, null)]
    public async Task WindowStatusResolvesAnyCatalogApplicationWithoutLaunching(
        string name,
        bool expectedInstalled,
        bool expectedVisible,
        string? expectedDisplayName)
    {
        var platform = new FakePlatform(Catalog)
        {
            Observations = name == "Steam" ? [Observation(foreground: false)] : [],
        };
        var provider = new WindowsInstalledApplicationOpenProvider(platform);

        ApplicationWindowStatusResult result = await provider.GetWindowStatusAsync(
            name, CancellationToken.None);

        Assert.Multiple(() =>
        {
            Assert.That(result.Verified, Is.True);
            Assert.That(result.Installed, Is.EqualTo(expectedInstalled));
            Assert.That(result.HasVisibleWindow, Is.EqualTo(expectedVisible));
            Assert.That(result.VisibleWindowCount, Is.EqualTo(expectedVisible ? 1 : 0));
            Assert.That(result.DisplayName, Is.EqualTo(expectedDisplayName));
            Assert.That(platform.ActivateCalls, Is.Zero);
            Assert.That(platform.FocusCalls, Is.Zero);
        });
    }

    [Test]
    public async Task AmbiguousWindowStatusDoesNotGuessOrLaunch()
    {
        var platform = new FakePlatform(Catalog);
        var provider = new WindowsInstalledApplicationOpenProvider(platform);

        ApplicationWindowStatusResult result = await provider.GetWindowStatusAsync(
            "Visual", CancellationToken.None);

        Assert.Multiple(() =>
        {
            Assert.That(result.Verified, Is.False);
            Assert.That(result.ErrorCode, Is.EqualTo(ApplicationOpenErrorCodes.ApplicationAmbiguous));
            Assert.That(platform.ActivateCalls, Is.Zero);
            Assert.That(platform.FocusCalls, Is.Zero);
        });
    }

    [Test]
    public async Task ExactDuplicateWindowStatusAggregatesUniqueVisibleWindowsWithoutLaunching()
    {
        InstalledApplicationEntry[] catalog =
        [
            new("Steam", "Valve.Steam.Client"),
            new("Steam", @"{7C5A40EF-A0FB-4BFC-874A-C0F2E0B9FA8E}\Steam\steam.exe"),
            new("Steam Support Center", "http://support.steampowered.com/"),
        ];
        var platform = new FakePlatform(catalog)
        {
            InventoryResolver = static entry => entry.Name == "Steam"
                ? [Observation(foreground: false)]
                : [],
        };
        var provider = new WindowsInstalledApplicationOpenProvider(platform);

        ApplicationWindowStatusResult result = await provider.GetWindowStatusAsync(
            "Steam", CancellationToken.None);

        Assert.Multiple(() =>
        {
            Assert.That(result.Verified, Is.True);
            Assert.That(result.Installed, Is.True);
            Assert.That(result.HasVisibleWindow, Is.True);
            Assert.That(result.VisibleWindowCount, Is.EqualTo(1));
            Assert.That(result.DisplayName, Is.EqualTo("Steam"));
            Assert.That(platform.InventoryCalls, Is.EqualTo(2));
            Assert.That(platform.ActivateCalls, Is.Zero);
            Assert.That(platform.FocusCalls, Is.Zero);
        });
    }

    [Test]
    public async Task ExistingVisibleApplicationIsFocusedWithoutASecondActivation()
    {
        var platform = new FakePlatform(Catalog)
        {
            Observations = [Observation(foreground: false)],
        };
        var provider = new WindowsInstalledApplicationOpenProvider(platform);

        ApplicationOpenResult result = await provider.OpenAsync(
            Request("Steam"),
            CancellationToken.None);

        Assert.Multiple(() =>
        {
            Assert.That(result.Succeeded, Is.True);
            Assert.That(result.Verified, Is.True);
            Assert.That(result.DisplayName, Is.EqualTo("Steam"));
            Assert.That(result.AlreadyRunning, Is.True);
            Assert.That(result.Receipt.ReusedExisting, Is.True);
            Assert.That(result.Receipt.LaunchIssued, Is.False);
            Assert.That(platform.ActivateCalls, Is.Zero);
            Assert.That(platform.FocusCalls, Is.EqualTo(1));
            Assert.That(platform.DelayCalls, Is.Zero);
        });
    }

    [Test]
    public void ExactDuplicateDisplayNamePicksALaunchableIdentityWithoutTreatingPartialNamesAsEquals()
    {
        InstalledApplicationEntry[] catalog =
        [
            new("Steam", "Valve.Steam.Client"),
            new("Steam", @"{7C5A40EF-A0FB-4BFC-874A-C0F2E0B9FA8E}\Steam\steam.exe"),
            new("Steam Support Center", "http://support.steampowered.com/"),
            new("Visual Studio", "VisualStudio"),
            new("Visual Studio Code", "VisualStudioCode"),
        ];

        InstalledApplicationResolution steam = InstalledApplicationResolver.ResolveForLaunch(
            "Steam",
            catalog);
        InstalledApplicationResolution visual = InstalledApplicationResolver.ResolveForLaunch(
            "Visual",
            catalog);

        Assert.Multiple(() =>
        {
            Assert.That(steam.Ambiguous, Is.False);
            Assert.That(steam.Entry?.AppUserModelId, Is.EqualTo("Valve.Steam.Client"));
            Assert.That(visual.Ambiguous, Is.True);
            Assert.That(visual.Entry, Is.Null);
        });
    }

    [Test]
    public async Task AbsentApplicationIsActivatedAndIndependentlyFocused()
    {
        var platform = new FakePlatform(Catalog)
        {
            ObservationAfterActivation = Observation(foreground: false),
        };
        var provider = new WindowsInstalledApplicationOpenProvider(platform);

        ApplicationOpenResult result = await provider.OpenAsync(
            Request("Steam"),
            CancellationToken.None);

        Assert.Multiple(() =>
        {
            Assert.That(result.Succeeded, Is.True);
            Assert.That(result.Verified, Is.True);
            Assert.That(result.AlreadyRunning, Is.False);
            Assert.That(result.Receipt.LaunchIssued, Is.True);
            Assert.That(result.Receipt.ReusedExisting, Is.False);
            Assert.That(platform.ActivateCalls, Is.EqualTo(1));
            Assert.That(platform.FocusCalls, Is.EqualTo(1));
            Assert.That(platform.DelayCalls, Is.Zero);
        });
    }

    [Test]
    public async Task ForegroundVerificationWaitsOnlyAfterAnUnconvergedImmediatePostread()
    {
        var platform = new FakePlatform(Catalog)
        {
            Observations = [Observation(foreground: false)],
            FocusRequiresDelay = true,
        };
        var provider = new WindowsInstalledApplicationOpenProvider(platform);

        ApplicationOpenResult result = await provider.OpenAsync(
            Request("Steam"),
            CancellationToken.None);

        Assert.Multiple(() =>
        {
            Assert.That(result.Succeeded, Is.True);
            Assert.That(result.Verified, Is.True);
            Assert.That(platform.ActivateCalls, Is.Zero);
            Assert.That(platform.FocusCalls, Is.EqualTo(1));
            Assert.That(platform.DelayCalls, Is.EqualTo(1));
        });
    }

    [Test]
    public async Task ActivationKeepsTheOriginalObservationTimeoutAfterTheImmediatePostread()
    {
        var platform = new FakePlatform(Catalog);
        var provider = new WindowsInstalledApplicationOpenProvider(platform);

        ApplicationOpenResult result = await provider.OpenAsync(
            Request("Steam"),
            CancellationToken.None);

        Assert.Multiple(() =>
        {
            Assert.That(result.Succeeded, Is.True);
            Assert.That(result.Verified, Is.False);
            Assert.That(result.ErrorCode, Is.EqualTo(
                ApplicationOpenErrorCodes.VerificationFailed));
            Assert.That(platform.ActivateCalls, Is.EqualTo(1));
            Assert.That(platform.DelayCalls, Is.EqualTo(28));
        });
    }

    [Test]
    public async Task MissingApplicationNeverActivatesAnApproximateTarget()
    {
        var platform = new FakePlatform(Catalog);
        var provider = new WindowsInstalledApplicationOpenProvider(platform);

        ApplicationOpenResult result = await provider.OpenAsync(
            Request("Definitely Missing"),
            CancellationToken.None);

        Assert.Multiple(() =>
        {
            Assert.That(result.Succeeded, Is.False);
            Assert.That(result.Verified, Is.False);
            Assert.That(result.ErrorCode, Is.EqualTo(ApplicationOpenErrorCodes.ApplicationNotFound));
            Assert.That(platform.ActivateCalls, Is.Zero);
        });
    }

    [Test]
    public async Task CatalogSnapshotContainsOnlyVerifiedUniquelyResolvableStartApplications()
    {
        InstalledApplicationEntry[] catalog =
        [
            .. Catalog,
            new("Duplicate", "Contoso.First"),
            new("Dúplicate", "Contoso.Second"),
        ];
        var provider = new WindowsInstalledApplicationOpenProvider(
            new FakePlatform(catalog));

        InstalledApplicationCatalogSnapshot snapshot =
            await provider.GetCatalogSnapshotAsync(CancellationToken.None);

        Assert.Multiple(() =>
        {
            Assert.That(snapshot.Verified, Is.True);
            Assert.That(snapshot.Complete, Is.True);
            Assert.That(snapshot.Names, Does.Contain("Paint"));
            Assert.That(snapshot.Names, Does.Contain("Spotify"));
            Assert.That(snapshot.Names, Does.Contain("Visual Studio Code"));
            Assert.That(snapshot.Names, Does.Contain("Configuración"));
            Assert.That(snapshot.Names, Does.Contain("Asistencia rápida"));
            Assert.That(snapshot.Names, Does.Not.Contain("Steam Support Center"));
            Assert.That(snapshot.Names, Does.Not.Contain("Duplicate"));
            Assert.That(snapshot.Names, Does.Not.Contain("Dúplicate"));
        });
    }

    [Test]
    public void CatalogSnapshotTruncatesDeterministicallyAtTheContractLimit()
    {
        InstalledApplicationEntry[] catalog = Enumerable
            .Range(0, ApplicationCatalogContract.MaximumNames + 2)
            .Select(static index => new InstalledApplicationEntry(
                $"Application {index:D4}",
                $"Contoso.Application.{index:D4}"))
            .ToArray();

        InstalledApplicationCatalogSnapshot snapshot =
            WindowsInstalledApplicationOpenProvider.CreateCatalogSnapshot(catalog);

        Assert.Multiple(() =>
        {
            Assert.That(snapshot.Verified, Is.True);
            Assert.That(snapshot.Complete, Is.False);
            Assert.That(
                snapshot.Names,
                Has.Count.EqualTo(ApplicationCatalogContract.MaximumNames));
            Assert.That(
                snapshot.Names
                    .Select(ApplicationCatalogContract.NormalizeName)
                    .Distinct(StringComparer.Ordinal)
                    .Count(),
                Is.EqualTo(snapshot.Names.Count));
        });
    }

    [Test]
    public async Task CatalogSnapshotFailsClosedWhenStartInventoryCannotBeRead()
    {
        var platform = new FakePlatform(Catalog)
        {
            CatalogFailure = new InvalidDataException("inventory unavailable"),
        };
        var provider = new WindowsInstalledApplicationOpenProvider(platform);

        InstalledApplicationCatalogSnapshot snapshot =
            await provider.GetCatalogSnapshotAsync(CancellationToken.None);

        Assert.Multiple(() =>
        {
            Assert.That(snapshot.Verified, Is.False);
            Assert.That(snapshot.Complete, Is.False);
            Assert.That(snapshot.Names, Is.Empty);
        });
    }

    [Test]
    public async Task CatalogSnapshotFailsClosedOnAUnicodeReplacementCharacter()
    {
        IReadOnlyList<InstalledApplicationEntry> corrupted =
        [
            new("Configuraci\uFFFDn", "windows.immersivecontrolpanel"),
            new(
                "Asistencia rápida",
                "MicrosoftCorporationII.QuickAssist_\uFFFD!App"),
        ];
        var provider = new WindowsInstalledApplicationOpenProvider(
            new FakePlatform(corrupted));

        InstalledApplicationCatalogSnapshot snapshot =
            await provider.GetCatalogSnapshotAsync(CancellationToken.None);

        Assert.Multiple(() =>
        {
            Assert.That(snapshot.Verified, Is.False);
            Assert.That(snapshot.Complete, Is.False);
            Assert.That(snapshot.Names, Is.Empty);
        });
    }

    private static ApplicationOpenRequest Request(string name) =>
        new(name, Guid.NewGuid().ToString("D"));

    private static InstalledApplicationObservation Observation(bool foreground) =>
        new(
            ProcessId: 4242,
            ProcessCreationTimeUtcTicks: DateTime.UtcNow.Ticks,
            ExecutablePath: @"C:\Program Files (x86)\Steam\steam.exe",
            WindowHandle: 73,
            Visible: true,
            Foreground: foreground);

    private sealed class FakePlatform(IReadOnlyList<InstalledApplicationEntry> catalog)
        : IInstalledApplicationPlatform
    {
        private long? _requestedForegroundHandle;

        public IReadOnlyList<InstalledApplicationObservation> Observations { get; set; } = [];

        public Func<
            InstalledApplicationEntry,
            IReadOnlyList<InstalledApplicationObservation>>
            ? InventoryResolver
        { get; init; }

        public InstalledApplicationObservation? ObservationAfterActivation { get; init; }

        public bool FocusRequiresDelay { get; init; }

        public int ActivateCalls { get; private set; }

        public int FocusCalls { get; private set; }

        public int DelayCalls { get; private set; }

        public int InventoryCalls { get; private set; }

        public Exception? CatalogFailure { get; init; }

        public ValueTask<IReadOnlyList<InstalledApplicationEntry>> ReadCatalogAsync(
            CancellationToken cancellationToken)
        {
            cancellationToken.ThrowIfCancellationRequested();
            if (CatalogFailure is not null)
            {
                return ValueTask.FromException<IReadOnlyList<InstalledApplicationEntry>>(
                    CatalogFailure);
            }

            return ValueTask.FromResult(catalog);
        }

        public IReadOnlyList<InstalledApplicationObservation> Inventory(
            InstalledApplicationEntry entry)
        {
            InventoryCalls++;
            return InventoryResolver?.Invoke(entry) ?? Observations;
        }

        public bool Activate(InstalledApplicationEntry entry)
        {
            ActivateCalls++;
            if (ObservationAfterActivation is not null)
            {
                Observations = [ObservationAfterActivation];
            }

            return true;
        }

        public void RequestForeground(long windowHandle)
        {
            FocusCalls++;
            _requestedForegroundHandle = windowHandle;
            if (!FocusRequiresDelay)
            {
                MarkForeground(windowHandle);
            }
        }

        public ValueTask DelayAsync(TimeSpan delay, CancellationToken cancellationToken)
        {
            cancellationToken.ThrowIfCancellationRequested();
            DelayCalls++;
            if (FocusRequiresDelay && _requestedForegroundHandle is long windowHandle)
            {
                MarkForeground(windowHandle);
            }
            return ValueTask.CompletedTask;
        }

        private void MarkForeground(long windowHandle)
        {
            Observations = Observations
                .Select(item => item.WindowHandle == windowHandle
                    ? item with { Foreground = true }
                    : item)
                .ToArray();
        }
    }
}
