/* Tiny global toast bus. Any module can call `pushToast({...})` without
 * needing a hook or context; the `<ToastHost />` component subscribes and
 * renders. We use a plain EventTarget so callers don't pay the React tree
 * cost — they just dispatch a CustomEvent and the host picks it up. */

import { useEffect, useState } from 'react';

export type ToastKind = 'error' | 'info' | 'success';

export interface ToastSpec {
  /** Identifier — autogenerated if omitted. Used to deduplicate rapidly-
   *  repeated toasts (e.g. polling failures spam). */
  id?: string;
  kind: ToastKind;
  msg: string;
  /** Optional auto-dismiss timeout in ms. Defaults to 4000ms. Pass 0 to
   *  keep it pinned until the user closes it. */
  ttlMs?: number;
}

export interface Toast extends Required<ToastSpec> {
  // wall-clock ts so the host can render age + drop expired entries.
  bornAt: number;
}

const BUS = new EventTarget();
const EV = 'gemma4:toast';

let _seq = 0;
function nextId(): string {
  _seq = (_seq + 1) & 0xffff;
  return `t${Date.now().toString(36)}${_seq.toString(36)}`;
}

export function pushToast(spec: ToastSpec): void {
  const t: Toast = {
    id: spec.id ?? nextId(),
    kind: spec.kind,
    msg: spec.msg,
    ttlMs: spec.ttlMs ?? 4000,
    bornAt: Date.now(),
  };
  BUS.dispatchEvent(new CustomEvent<Toast>(EV, { detail: t }));
}

/** Convenience for the most common case: a fetch-failure toast. */
export function toastError(msg: string): void {
  pushToast({ kind: 'error', msg });
}

export function useToasts(): { toasts: Toast[]; dismiss: (id: string) => void } {
  const [toasts, setToasts] = useState<Toast[]>([]);

  useEffect(() => {
    const onPush = (e: Event) => {
      const detail = (e as CustomEvent<Toast>).detail;
      setToasts((prev) => {
        // dedupe by id: replace if exists so the bornAt updates
        const filtered = prev.filter((t) => t.id !== detail.id);
        return [...filtered, detail];
      });
    };
    BUS.addEventListener(EV, onPush);
    return () => BUS.removeEventListener(EV, onPush);
  }, []);

  // GC expired toasts on a 500ms tick. Cheap and bounded — the toast list
  // is never more than a handful of entries.
  useEffect(() => {
    const id = window.setInterval(() => {
      const now = Date.now();
      setToasts((prev) =>
        prev.filter((t) => t.ttlMs === 0 || now - t.bornAt < t.ttlMs)
      );
    }, 500);
    return () => window.clearInterval(id);
  }, []);

  const dismiss = (id: string) => setToasts((p) => p.filter((t) => t.id !== id));

  return { toasts, dismiss };
}
