"""Explicit human-authored seen scenarios for every authenticated operation.

These rows are development data.  They are intentionally readable and kept
separate from every blind holdout so reviewers can inspect whether each phrase
really asks for the named operation before any product change is measured.
"""

from __future__ import annotations


# operation -> (language, natural user request)
SEEN_UTTERANCES: dict[str, tuple[str, str]] = {
    "app.close": ("es", "Cierra la ventana de Bloc de notas."),
    "app.installed": ("en", "Check whether Obsidian is installed without opening it."),
    "app.open": ("es", "Abre la calculadora."),
    "audio.microphone.mute": ("spanglish", "Mutea el microphone del computador."),
    "audio.mute": ("es", "Silencia el audio del computador."),
    "audio.status": ("en", "Tell me the current speaker volume and mute state."),
    "audio.volume": ("es", "Pon el volumen del computador al 37 por ciento."),
    "audio.volume.adjust": ("spanglish", "Baja el volume del PC en 8 puntos."),
    "backup.create": (
        "es",
        "Crea una copia privada del archivo que acabo de seleccionar y verifica su hash.",
    ),
    "backup.known.create": ("en", "Create a verified private ZIP backup of my Documents folder."),
    "backup.known.list": ("es", "Lista mis copias ZIP de carpetas conocidas y verifica sus hashes."),
    "backup.known.restore.latest": (
        "spanglish",
        "Restore el backup ZIP más reciente de Documents en una carpeta privada nueva.",
    ),
    "backup.known.verify.latest": ("es", "Verifica el backup ZIP más reciente de Documentos."),
    "backup.list": ("en", "List my verified private backups, newest first."),
    "backup.restore": ("es", "Restaura el backup privado que acabo de elegir en un destino nuevo."),
    "backup.verify": ("spanglish", "Verify el tamaño y SHA-256 del backup que seleccioné."),
    "bluetooth.device.list": ("es", "Muéstrame los dispositivos Bluetooth visibles."),
    "bluetooth.device.pair": ("en", "Pair the Bluetooth headset named Living Room Buds."),
    "bluetooth.radio.set": ("es", "Enciende el Bluetooth y comprueba que quede encendido."),
    "browser.control": ("spanglish", "Go back una página en la pestaña actual."),
    "browser.navigate": ("es", "Navega la sesión web actual a https://example.com/docs."),
    "browser.navigate.named": ("en", "Open https://example.com/account specifically in Opera."),
    "browser.page.read": ("es", "Lee el título, la URL y el texto visible de la página actual."),
    "browser.tabs.list": ("spanglish", "List las pestañas abiertas de la sesión web local."),
    "calendar.event.create": (
        "es",
        "Crea en mi calendario un evento llamado Revisión mañana de nueve a diez.",
    ),
    "calendar.event.list": ("en", "List my calendar events for tomorrow without changing them."),
    "capture.active.window": ("es", "Captura solamente la ventana que está activa."),
    "capture.screenshot": ("spanglish", "Take un screenshot de todo el escritorio."),
    "clipboard.copy": ("es", "Copia la selección actual al portapapeles."),
    "clipboard.paste": ("en", "Paste the current clipboard into the focused field."),
    "clipboard.read.text": ("es", "Lee el texto que tengo ahora en el portapapeles."),
    "clipboard.write.text": ("spanglish", "Pon en el clipboard el texto literal reunión a las cinco."),
    "email.latest.read": ("es", "Lee el correo más reciente de mi Outlook."),
    "email.latest.reply": (
        "en",
        "Reply to my latest Outlook email with: I received it, thank you.",
    ),
    "filesystem.copy": ("es", "Copia el archivo seleccionado a la carpeta archivo dentro del sandbox."),
    "filesystem.create.directory": ("spanglish", "Create una carpeta del sandbox llamada pruebas agosto."),
    "filesystem.file.open.latest": ("es", "Abre el archivo modificado más recientemente de Descargas."),
    "filesystem.folder.open": ("en", "Open my Downloads folder in File Explorer."),
    "filesystem.hash": ("es", "Calcula el SHA-256 del archivo que acabo de seleccionar."),
    "filesystem.known.duplicates": ("spanglish", "Find duplicate files en Descargas sin borrarlos."),
    "filesystem.known.search": ("es", "Busca en Documentos un archivo llamado informe final."),
    "filesystem.known.trash.named": (
        "en",
        "Move the uniquely named file draft-old.txt from Downloads to the private trash.",
    ),
    "filesystem.list": ("es", "Lista el contenido de la carpeta raíz del sandbox."),
    "filesystem.move": ("spanglish", "Move el archivo seleccionado a archivo/terminado.txt dentro del sandbox."),
    "filesystem.path.ensure.absent": (
        "es",
        "Asegúrate de que C:\\Users\\Public\\Temp\\baxy-prueba.txt no exista y usa la papelera recuperable si existe.",
    ),
    "filesystem.read.text": ("en", "Read the selected UTF-8 text file and verify its hash."),
    "filesystem.sandbox.append.named": (
        "es",
        "Añade la línea revisión completa al archivo único registro.txt del sandbox.",
    ),
    "filesystem.sandbox.diff.named": (
        "spanglish",
        "Compare notas-a.txt con notas-b.txt in the sandbox y dime las líneas distintas.",
    ),
    "filesystem.sandbox.move.named": (
        "es",
        "Mueve el archivo único borrador.txt del sandbox a archivo/borrador.txt.",
    ),
    "filesystem.search": ("en", "Search the sandbox for names containing invoice."),
    "filesystem.trash.commit": ("es", "Confirma la selección de papelera que acabo de revisar."),
    "filesystem.trash.prepare": (
        "spanglish",
        "Prepare el archivo seleccionado para enviarlo a la papelera, pero no lo muevas aún.",
    ),
    "filesystem.trash.restore": ("es", "Restaura de la papelera privada el archivo que acabo de seleccionar."),
    "filesystem.write.text": (
        "en",
        "Write the text quarterly review into reports/review.txt in the sandbox.",
    ),
    "game.catalog.list": ("es", "Lista mi catálogo local de Steam."),
    "game.install.cancel": ("spanglish", "Cancel la descarga de Steam del AppID 730."),
    "game.install.cancel.active": ("es", "Cancela todas las descargas activas de Steam."),
    "game.install.commit": ("en", "Confirm the Steam installation I just prepared."),
    "game.install.named": ("es", "Instala Portal desde mi biblioteca de Steam si lo tengo comprado."),
    "game.install.prepare": ("spanglish", "Prepare la instalación del AppID 620 sin descargar todavía."),
    "game.install.status": ("es", "Dime el progreso de instalación en Steam del AppID 730."),
    "game.installed.named": ("en", "Check whether Rocket League is installed without launching it."),
    "game.launch": ("es", "Inicia el juego Cuphead desde Steam."),
    "game.purchase.commit": ("spanglish", "Confirm the game purchase que acabo de revisar al precio exacto mostrado."),
    "game.purchase.prepare": ("es", "Prepara la compra de Hades y muéstrame el precio sin comprarlo."),
    "input.key.press": ("en", "Press Control Shift Escape in the focused window."),
    "input.keyboard.layout": ("es", "Cambia el teclado de la ventana activa a español."),
    "input.keyboard.open": ("spanglish", "Open el teclado en pantalla de Windows."),
    "input.keyboard.status": ("es", "Dime qué distribución de teclado usa la ventana enfocada."),
    "input.pointer.control": ("en", "Move the mouse pointer to the center of the screen."),
    "input.select.all": ("es", "Selecciona todo en el control que está enfocado."),
    "input.text.type": ("spanglish", "Type el texto literal pedido recibido en el campo enfocado."),
    "input.visible.click": ("es", "Haz clic una sola vez en el botón visible que dice Continuar."),
    "media.control": ("en", "Pause the current Windows media session."),
    "media.play.exact": ("es", "Reproduce el resultado musical exacto que acabo de seleccionar en Spotify."),
    "media.play.query": ("spanglish", "Play la canción Space Oddity en Spotify."),
    "media.play.youtube": ("es", "Busca y reproduce en YouTube el video oficial de Space Oddity."),
    "media.seek.relative": ("en", "Skip forward thirty seconds in the current media session."),
    "media.status": ("es", "Dime qué está sonando ahora y si está pausado."),
    "memory.correct": ("spanglish", "Corrige mi memory: mi color favorito ahora es verde, no azul."),
    "memory.disable": ("es", "Desactiva la memoria local de BAXY."),
    "memory.enable": ("en", "Enable BAXY's private local memory."),
    "memory.export": ("es", "Exporta una copia privada de todo lo que BAXY recuerda de mí."),
    "memory.forget": ("spanglish", "Forget todo lo que recuerdas sobre mi proyecto Atlas."),
    "memory.list": ("es", "Muéstrame la lista de recuerdos locales que guardaste."),
    "memory.recall": ("en", "What do you remember about my preferred editor?"),
    "memory.save": ("es", "Recuerda que mi editor preferido es Visual Studio Code."),
    "memory.sensitive.save": ("spanglish", "Guarda como sensitive memory que mi alergia es al maní."),
    "memory.session.clear": ("es", "Borra solamente la memoria temporal de esta conversación."),
    "memory.status": ("en", "Tell me whether local memory is enabled and what its limits are."),
    "message.recipient.resolve": (
        "es",
        "Busca exactamente a Camila en WhatsApp y dime si hay un único contacto, sin enviar nada.",
    ),
    "message.send": ("spanglish", "Send a Camila por WhatsApp: llegaré en veinte minutos."),
    "network.dns.status": ("es", "Dime qué servidores DNS usan ahora las interfaces activas."),
    "network.ip.list": ("en", "List this computer's active unicast IP addresses."),
    "network.ping": ("es", "Haz un ping a example.com y dime la latencia."),
    "network.port.list": ("spanglish", "List los puertos TCP y UDP que están escuchando localmente."),
    "network.status": ("es", "Comprueba el estado general de la conexión de red."),
    "note.create": ("en", "Create a note titled Trip with the content bring the blue backpack."),
    "note.list": ("es", "Lista mis notas locales activas."),
    "note.read": ("spanglish", "Read la nota que se llama Viaje."),
    "note.restore": ("es", "Restaura desde la papelera la nota titulada Viaje."),
    "note.search": ("en", "Search my local notes for the phrase blue backpack."),
    "note.trash": ("es", "Mueve a la papelera la nota titulada Borrador viejo."),
    "note.update": (
        "spanglish",
        "Update la nota Viaje: título Viaje final y contenido llevar mochila azul y pasaporte.",
    ),
    "notification.cancel.at": ("es", "Cancela la alarma de BAXY de las cinco y media de la tarde."),
    "notification.cancel.latest": ("en", "Cancel the most recently created BAXY alarm."),
    "notification.diagnose": ("es", "Diagnostica por qué no sonó mi última alarma de BAXY."),
    "notification.dismiss": ("spanglish", "Dismiss el recordatorio vencido que acabo de seleccionar."),
    "notification.list.due": ("es", "Lista los recordatorios vencidos que aún no descarté."),
    "notification.schedule": ("en", "Schedule an audible alarm for seven thirty tomorrow morning."),
    "ocr.read": ("es", "Toma una captura y extrae todo el texto visible con OCR local en español."),
    "office.document.create": (
        "spanglish",
        "Create un documento de Word llamado Resumen con el texto Reunión completada.",
    ),
    "office.document.read": ("es", "Lee el documento que acabo de crear y dame su contenido estructurado."),
    "package.install.commit": ("en", "Confirm the winget package installation I just reviewed."),
    "package.install.prepare": ("es", "Prepara la instalación exacta de Microsoft.PowerToys sin instalar aún."),
    "peripheral.list": ("spanglish", "List los teclados y mouse conectados al computador."),
    "peripheral.print": ("es", "Imprime el documento que seleccioné en la impresora Oficina."),
    "peripheral.scan": ("en", "Scan one page using the connected scanner named Office Scanner."),
    "reminder.create": ("es", "Crea un recordatorio local durable para pagar el arriendo mañana a las nueve."),
    "reminder.delete": ("spanglish", "Delete de forma recuperable el recordatorio llamado Pagar arriendo."),
    "reminder.list": ("es", "Lista mis recordatorios locales programados."),
    "reminder.resolve.exact": (
        "en",
        "Find the exact reminder titled Pay rent and return its current identity without changing it.",
    ),
    "reminder.restore": ("es", "Restaura el recordatorio eliminado llamado Pagar arriendo."),
    "routine.delete": ("spanglish", "Delete de forma recuperable la rutina llamada Música de trabajo."),
    "routine.list": ("es", "Lista las rutinas locales que tengo creadas."),
    "routine.phrase.create": (
        "en",
        "Create a routine named Focus music that plays Spotify when I say start focus.",
    ),
    "routine.read": ("es", "Lee los metadatos de la rutina exacta llamada Música de trabajo."),
    "routine.resolve.exact": (
        "spanglish",
        "Resolve la rutina exacta Música de trabajo sin ejecutarla.",
    ),
    "routine.restore": ("es", "Restaura deshabilitada la rutina eliminada Música de trabajo."),
    "routine.set.enabled": ("en", "Disable the routine named Focus music without running it."),
    "streaming.navigate": (
        "es",
        "Navega mi sesión autenticada de streaming a https://www.netflix.com/browse.",
    ),
    "streaming.play.named": ("spanglish", "Play The Crown en mi sesión autenticada de Netflix."),
    "system.application.crash.diagnose": (
        "es",
        "Busca fallos recientes de aplicaciones en Windows y dime cuál se bloqueó.",
    ),
    "system.identity": ("en", "Tell me the effective Windows user and domain running BAXY."),
    "system.power": ("es", "Bloquea esta sesión de Windows ahora."),
    "system.process.list": ("spanglish", "List los procesos que más memoria están usando."),
    "system.process.terminate.named": (
        "es",
        "Fuerza el cierre de notepad.exe y verifica que ese proceso desaparezca.",
    ),
    "system.recyclebin.empty": ("en", "Empty the Windows Recycle Bin and verify it is empty."),
    "system.settings.adjust": ("es", "Sube el brillo de la pantalla en diez puntos."),
    "system.settings.set": ("spanglish", "Turn on la luz nocturna de Windows."),
    "system.settings.status": ("es", "Dime el brillo actual de cada monitor compatible."),
    "system.status": ("en", "Show me this computer's current CPU, memory, disk, battery, and GPU status."),
    "system.time": ("es", "Dime la fecha y la hora local actuales."),
    "task.complete": ("spanglish", "Mark complete la tarea exacta llamada Enviar informe."),
    "task.create": ("es", "Crea una tarea llamada Enviar informe con fecha para el viernes."),
    "task.delete": ("en", "Move the exact task Send report to the recoverable trash."),
    "task.list": ("es", "Lista mis tareas locales que siguen abiertas."),
    "task.reopen": ("spanglish", "Reopen la tarea completada llamada Enviar informe."),
    "task.resolve.exact": (
        "es",
        "Resuelve la tarea exacta titulada Enviar informe sin modificarla.",
    ),
    "task.restore": ("en", "Restore the deleted task titled Send report."),
    "task.search": ("es", "Busca en mis tareas locales la frase informe trimestral."),
    "task.update": (
        "spanglish",
        "Update la tarea Enviar informe: nuevo título Enviar informe final y fecha el lunes.",
    ),
    "vision.describe": ("es", "Toma una captura y describe localmente lo que aparece en la imagen."),
    "web.search": ("en", "Search the web for the official Python documentation."),
    "wifi.connect": ("es", "Conecta el perfil Wi-Fi que acabo de seleccionar."),
    "wifi.connect.named": ("spanglish", "Connect al perfil Wi-Fi guardado llamado Casa."),
    "wifi.disconnect": ("es", "Desconecta el Wi-Fi y comprueba que quede desconectado."),
    "wifi.ensure.connected": ("en", "Check that Wi-Fi is already connected without changing it."),
    "wifi.profile.list": ("es", "Lista los perfiles Wi-Fi guardados sin mostrar credenciales."),
    "wifi.status": ("spanglish", "Tell me el estado actual de la conexión Wi-Fi."),
    "window.active": ("es", "Dime qué ventana está activa ahora y cuál es su geometría."),
    "window.application.status": (
        "en",
        "Check whether Visual Studio Code currently has a visible window without opening it.",
    ),
    "window.focus": ("es", "Enfoca la ventana de Bloc de notas."),
    "window.maximize": ("spanglish", "Maximize la ventana de Bloc de notas."),
    "window.minimize": ("es", "Minimiza la ventana de Bloc de notas."),
    "window.move": ("en", "Move the Notepad window to desktop coordinates 120, 80."),
    "window.resize": ("es", "Redimensiona la ventana de Bloc de notas a 900 por 600 píxeles."),
    "window.resolve": (
        "spanglish",
        "Resolve las ventanas visibles de notepad.exe y devuelve sus identificadores.",
    ),
    "window.restore": ("es", "Restaura la ventana minimizada de Bloc de notas."),
}
