"""Observe raw generation and native parsing for three exact local493 requests."""
from pathlib import Path
import copy
import hashlib
import json
import os
import sys
import time
import threading

root = Path(__file__).resolve().parents[1]
sys.path[:0] = [str(root), str(root / 'src')]
import psutil
from baxy_mind.llm import LlmRuntime
from scripts.measure_mind_budget import ProcessTreeGpuSampler, RamSampler

base = root / 'artifacts/comprobaciones/C03'
local = Path(os.environ['LOCALAPPDATA']) / 'BAXY'
out = base / 'astra-gemma-parse494'
private = local / 'C03-gemma-parse494-private'
out.mkdir(exist_ok=False)
assert private.is_dir() and not (private / 'cases.json').exists()

def sha(path):
    with Path(path).open('rb') as stream:
        return hashlib.file_digest(stream, 'sha256').hexdigest()

def write(path, value):
    path.write_text(json.dumps(value, ensure_ascii=False, indent=2) + '\n', encoding='utf-8')

def append(path, value):
    with path.open('a', encoding='utf-8') as stream:
        stream.write(json.dumps(value, ensure_ascii=False) + '\n')

cases = json.loads((local / 'C03-gemma-native493-private/cases.json').read_text(encoding='utf-8'))
cases = [case for case in cases if case['variant'] == 'typed'
         and case['id'] in {'owner46-seed0', 'owner51-seed0', 'volume-unmute'}]
assert len(cases) == 3
for case in cases:
    case['payload'] = copy.deepcopy(case['payload'])
    case['payload']['verbose'] = True
write(private / 'cases.json', cases)
manifest = Path(os.environ['LOCALAPPDATA']) / 'BAXYRuntime/mind-runtime-v1.json'
manifest_sha = sha(manifest)
model = Path('D:/BAXYRuntime/experiments/models/baxy-gemma4-e2b-published-f9b84ecd/gemma-4-E2B-it-Q4_K_M.gguf')
server = Path('D:/BAXYRuntime/assets/llama-v0.4.0-b10809-cuda12.4/llama-server.exe')
assert sha(model) == '9d4a5a653f2733a5faeb5f58a0e30bc064dfd569b0059cabb2547dbc4ba0f4b7'
assert sha(server) == 'cb29f66008d4d73cce17cab2c2569ab318eb244b0b2ca2a15024b44d90dfcd3f'
write(out / 'PREREG.json', {
    'method': 'Three exact typed payloads493. Only verbose:true is added to expose raw content alongside parsed tool calls. No generated text sent outside this PC. No providers, product edits, parser changes, prompt changes or sampler changes.',
    'source_evidence': 'Pinned5266f24da server-task.cpp414-459:verbose appends __verbose only; server-context.cpp2097-2116 copies generated_text; server-task.cpp339-365 exposes raw content/stop_type/truncated. force_pure_content changes grammar/template, so it is not used.',
    'hypothesis': 'Determine whether extra native calls were generated by Gemma or inserted by native parsing; do not attribute a cause from parsed output alone.',
    'sources': json.loads((private / 'SOURCES.json').read_text(encoding='utf-8')),
    'user_reports': ['https://github.com/ggml-org/llama.cpp/issues/21375', 'https://github.com/ggml-org/llama.cpp/issues/22786'],
    'report_scope': 'Other versions/models/hardware; reproduction hypotheses, not proof of the cause here.',
    'cases_sha256': sha(private / 'cases.json'), 'model_sha256': sha(model),
    'server_sha256': sha(server), 'manifest_sha256': manifest_sha,
    'limits': {'gpu_stop_mib': 3800, 'minimum_free_ram_mib': 768, 'request_seconds': 90},
    'private': str(private),
})
for key in list(os.environ):
    if key.startswith('BAXY_MIND_'):
        os.environ.pop(key)
os.environ.update(BAXY_MIND_LLM_GGUF=str(model), BAXY_MIND_LLAMA_SERVER=str(server),
                  BAXY_MIND_NGL='99', BAXY_MIND_KV_CACHE_TYPE='q8_0')

class Measured(LlmRuntime):
    def _server_command(self):
        command = super()._server_command()
        command[command.index('--reasoning') + 1] = 'on'
        command[command.index('--reasoning-budget') + 1] = '-1'
        command += ['--reasoning-format', 'deepseek', '--lazy-mode', 'on',
                    '--log-file', str(private / 'server.log')]
        write(private / 'effective-server-command.json', command)
        return command

client = Measured()
gpu = ProcessTreeGpuSampler(os.getpid())
ram = RamSampler(os.getpid())
stop = threading.Event()
violations = []

def watch():
    while not stop.wait(.25):
        if gpu.peak_mib is not None and gpu.peak_mib >= 3800:
            violations.append('gpu_bound')
        if psutil.virtual_memory().available < 768 * 2**20:
            violations.append('free_ram_bound')
        if violations:
            client.close()
            return

guard = threading.Thread(target=watch, daemon=True)
started = time.monotonic()
try:
    gpu.start(); ram.start(); guard.start()
    client.start_warmup(); assert client.wait_warmup(90)
    for case in cases:
        client.begin_request(90)
        before = time.monotonic()
        try:
            response = client._post(case['payload'])
        finally:
            client.end_request()
        row = {'id': case['id'], 'seconds': round(time.monotonic() - before, 3), 'response': response}
        append(private / 'posts.jsonl', {'payload': case['payload'], **row})
        append(out / 'replies.jsonl', row)
        print(json.dumps({'id': case['id'], 'verbose_present': '__verbose' in response,
                          'calls': len(response['choices'][0]['message'].get('tool_calls', []))}), flush=True)
        assert '__verbose' in response, 'No raw output metadata; do not infer parsing cause'
        if violations:
            break
finally:
    stop.set(); client.close(); guard.join(timeout=5); gpu.stop(); ram.stop()
    write(out / 'RESOURCES.json', {'violations': violations, 'gpu_peak_mib': gpu.peak_mib,
                                  'ram_peak_mib': ram.peak_mib,
                                  'seconds': round(time.monotonic() - started, 3),
                                  'manifest_unchanged': sha(manifest) == manifest_sha})
write(out / 'PINS.json', {p.name: sha(p) for p in out.iterdir() if p.is_file() and p.name != 'PINS.json'})
