"""Fail-closed file identities for reproducible historical tooling."""

from __future__ import annotations

import hashlib
import json
import re
from dataclasses import dataclass
from pathlib import Path

_SHA256 = re.compile(r"[0-9a-f]{64}\Z")


@dataclass(frozen=True, slots=True)
class FrozenFile:
    path: Path
    sha256: str


def _contract(
    repository_root: Path,
    protocol_path: Path,
    file_id: str,
) -> FrozenFile:
    protocol = json.loads(protocol_path.read_text(encoding="utf-8"))
    records = protocol.get("frozen_files")
    record = records.get(file_id) if isinstance(records, dict) else None
    if not isinstance(record, dict):
        raise RuntimeError(f"frozen_file_contract_missing:{file_id}")

    location = record.get("canonical_location")
    expected_sha256 = record.get("sha256")
    if (
        not isinstance(location, str)
        or not location
        or Path(location).is_absolute()
        or ".." in Path(location).parts
        or not isinstance(expected_sha256, str)
        or _SHA256.fullmatch(expected_sha256) is None
    ):
        raise RuntimeError(f"frozen_file_contract_invalid:{file_id}")

    root = repository_root.resolve(strict=True)
    path = (root / location).resolve(strict=False)
    if not path.is_relative_to(root):
        raise RuntimeError(f"frozen_file_outside_repository:{file_id}")
    return FrozenFile(path=path, sha256=expected_sha256)


def _sha256(payload: bytes) -> str:
    return hashlib.sha256(payload).hexdigest()


def _file_sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def verify_frozen_file(
    repository_root: Path,
    protocol_path: Path,
    file_id: str,
) -> Path:
    """Return the declared file only when its physical bytes still match."""

    contract = _contract(repository_root, protocol_path, file_id)
    try:
        digest = _file_sha256(contract.path)
    except OSError as error:
        raise RuntimeError(f"frozen_file_unavailable:{file_id}") from error
    if digest != contract.sha256:
        raise RuntimeError(f"frozen_file_drift:{file_id}")
    return contract.path


def verify_frozen_payload(
    repository_root: Path,
    protocol_path: Path,
    file_id: str,
    payload: bytes,
) -> Path:
    """Return the declared destination only when generated bytes match."""

    contract = _contract(repository_root, protocol_path, file_id)
    if _sha256(payload) != contract.sha256:
        raise RuntimeError(f"frozen_file_drift:{file_id}")
    return contract.path
