"""Pools de exemplars multilingües (ES/EN/spanglish) para el router de intención.

Ley aplicada: la detección de forma/intención se hace por similitud de
embeddings contra estos pools, NUNCA por coincidencia de frases. Los textos de
abajo son anclas semánticas del espacio de embeddings, no patrones de matching.

Reglas de honestidad:
- Ningún exemplar puede ser igual (normalizado) a un texto de los oráculos
  congelados; el runner verifica la disyunción y aborta si hay colisión.
- Los pools ABSTAIN__* son clases distractoras: si ganan, el router se abstiene
  (fail-closed) y la entrada pasa a la capa superior (LLM o rechazo).
"""

POSITIVE_POOLS: dict[str, list[str]] = {
    "system.time": [
        "qué hora es",
        "dime la hora actual",
        "me dices qué hora es ahora",
        "what time is it",
        "tell me the current time",
        "what's the time right now",
        "hora local por favor",
        "puedes decirme la hora",
    ],
    "note.create": [
        "crea una nota que diga comprar detergente",
        "make a note that says call the dentist",
        "anota que el jueves tengo turno médico",
        "créame una nota con el título reunión de equipo",
        "new note: ideas para el regalo de papá",
        "apunta esto: las llaves quedaron en el cajón de arriba",
        "toma nota de que mañana viene el técnico del gas",
        "guarda una nota llamada compras con leche huevos y arroz",
        "can you create a note saying pay the rent on friday",
        "haz una nota: cumpleaños de Sofía el 12 de agosto",
        "escribe una nota que diga regar las plantas el domingo",
        "write down: buy milk tomorrow morning",
        "quiero una nota nueva que diga estudiar para el examen de cálculo",
        "hazme una note que diga practice english every day",
        "nota nueva: devolver el libro a la biblioteca",
        "please note that the wifi router needs a restart weekly",
    ],
    "system.status:cpu": [
        "cuánto cpu estoy usando ahora",
        "uso de cpu por favor",
        "how busy is my processor right now",
        "qué tan cargado anda el procesador",
        "muéstrame el uso del procesador",
        "current cpu load",
        "cuántos núcleos tiene el procesador de esta máquina y qué modelo es",
        "check el cpu usage porfa",
    ],
    "system.status:memory": [
        "cuánta ram tengo instalada",
        "how much ram is in use right now",
        "cuánta memoria ram libre queda en el sistema",
        "dime la ram total de este equipo",
        "muéstrame cuánta memoria estoy ocupando",
        "ram disponible ahora mismo",
        "how much memory does this pc have",
    ],
    "system.status:cpu_memory": [
        "revisa cpu y ram",
        "show me cpu and memory usage together",
        "cómo van el procesador y la memoria",
        "chequea la ram y el cpu por favor",
        "cuánta memoria y cpu estoy usando",
        "check the cpu and the ram",
    ],
    "system.status:os_memory": [
        "qué windows tengo y cuánta ram tiene esta máquina",
        "what windows version am i on and how much ram do i have",
        "versión de windows y memoria ram del equipo",
    ],
    "system.status:disk": [
        "cuánto espacio libre queda en el disco",
        "free disk space please",
        "cuánto disco me queda disponible",
        "espacio disponible en la unidad c",
        "how much storage space is left on this pc",
        "queda mucho espacio en el disco duro?",
    ],
    "system.status:battery": [
        "cuánta batería le queda al equipo",
        "battery level please",
        "está cargando la batería ahora",
        "cómo anda la batería del notebook",
        "me alcanza la batería para un rato más?",
        "porcentaje de batería actual",
        "how much battery is left",
        "queda poca batería?",
        "nivel de carga de la batería",
    ],
    "system.status:os": [
        "qué versión de windows tengo instalada",
        "which windows version am i running",
        "dime la versión del sistema operativo",
        "what build of windows is this",
    ],
    "system.status:summary": [
        "cómo está la pc en general",
        "estado del sistema por favor",
        "how is my computer doing",
        "dame el estado general del equipo",
        "revisa el estado de mi computadora",
        "overall system status",
        "cómo anda el sistema, todo bien?",
    ],
    "system.status:gpu_identity": [
        "qué gpu tiene instalada esta computadora",
        "dime cuál es mi tarjeta gráfica",
        "which graphics card do i have",
        "cuánta vram tiene mi tarjeta de video",
        "modelo de mi gpu por favor",
        "what gpu is in this machine",
    ],
    "system.status:gpu_usage": [
        "uso de gpu ahora",
        "cuánta vram estoy usando",
        "show vram usage",
        "qué tan ocupada está la gpu",
        "revisa cómo va la gpu",
        "gpu usage right now",
        "chequea la vram porfa",
    ],
    "audio.volume": [
        "pon el volumen al 55",
        "volumen al 80 por ciento",
        "set the volume to 30 percent",
        "sube el volumen a 90",
        "deja el volumen en 40",
        "put the volume at 65",
        "bájale el volumen al 20",
        "volumen al máximo",
        "pon el sonido a la mitad",
        "volume 70 please",
        "ponle volumen bajo",
        "quiero el volumen alto",
        "ajusta el volumen al 35",
        "sube el volumen al máximo por favor",
        "baja el volumen al mínimo",
        "pon el volumen del equipo al mínimo",
        "deja el sonido a la mitad",
        "sube el sonido hasta el tope",
        "turn the volume to the max",
    ],
    "audio.mute": [
        "silencia el audio de la pc",
        "mute the computer sound completely",
        "mutea el sonido",
        "unmute please",
        "quita el silencio del audio",
        "activa el sonido de nuevo",
        "pon en mudo el equipo",
        "desmutea el audio",
        "apaga el sonido del sistema",
        "turn the sound back on",
    ],
    "audio.status": [
        "en cuánto está el volumen",
        "what is the current volume level",
        "está silenciado el audio ahora?",
        "dime el nivel de volumen actual",
        "is the sound muted right now",
        "a qué volumen está el sonido",
        "cómo está el audio, muteado o no?",
        "muéstrame el volumen actual",
        "muestra el nivel de volumen",
        "show me the volume",
        "ver el volumen del sistema",
        "qué volumen tiene puesto la pc",
    ],
    "memory.save": [
        "recuerda que mi color favorito es el verde",
        "remember that i park on level 3",
        "guarda que uso talla m de polera",
        "acuérdate de que prefiero respuestas cortas",
        "memoriza que mi perro se llama Rocky",
        "recuerda para siempre que mi equipo es River",
        "remember my favorite pizza is pepperoni",
        "guárdate que trabajo de noche los martes",
        "acuérdate que el cumpleaños de mamá es en marzo",
        "keep in mind that i study medicine",
        "recuerda que mi cumpleaños es el 5 de mayo",
        "recordá que prefiero el café sin azúcar",
        "recuerda que no me gusta que abran juegos pesados",
        "guarda que no quiero notificaciones de noche",
        "recuerda durante esta sesión que mi proyecto se llama atlas",
        "remember that i don't eat meat",
        "acuérdate de esto: mi contraseña del router la cambié en junio",
    ],
    "memory.recall": [
        "qué sabes de mi color favorito",
        "what did i tell you about my sister",
        "recuérdame qué talla uso",
        "qué te dije sobre mis horarios de trabajo",
        "qué recuerdas de mis preferencias",
        "do you remember what my dog is called",
        "qué guardaste sobre mi cumpleaños",
        "dime qué recuerdos tienes guardados de mí",
        "cuál era mi comida favorita según lo que te conté",
    ],
    "memory.forget": [
        "olvida mi color favorito",
        "forget what i told you about my job",
        "borra lo que sabes de mi dirección",
        "elimina el recuerdo de mi talla",
        "olvídate de que te conté lo de mi hermana",
        "delete what you know about my schedule",
    ],
    "memory.correct": [
        "no, mi color favorito ahora es el azul, corrígelo",
        "actually i live in valparaíso now, update that memory",
        "corrige: mi gata se llama Luna, no Nina",
        "eso está mal, mi turno es de mañana, actualízalo",
        "update it: my favorite team is Boca now",
    ],
}

# Clases distractoras: si alguna gana, el router se ABSTIENE (fail-closed).
ABSTAIN_POOLS: dict[str, list[str]] = {
    "ABSTAIN__time_knowledge": [
        "qué es el tiempo",
        "explícame cómo funcionan las zonas horarias",
        "what is utc time",
        "por qué cambia la hora en invierno",
        "qué hora será en tokio mañana",
    ],
    "ABSTAIN__media_control": [
        "pausa la música un momento",
        "play some music",
        "siguiente canción por favor",
        "reproduce mi playlist de estudio",
        "stop the video",
        "pon una canción de los beatles",
        "dale play a spotify",
        "salta este tema",
    ],
    "ABSTAIN__app_specific_audio": [
        "sube el volumen de spotify",
        "mute discord please",
        "baja el audio del navegador",
        "lower the volume of chrome only",
        "silencia la pestaña de youtube",
        "ponle volumen al juego nomás",
        "silencia las notificaciones nada más",
        "mute notifications only",
    ],
    "ABSTAIN__relative_volume": [
        "sube el volumen",
        "bájale un poco",
        "más fuerte por favor",
        "turn it up a bit",
        "baja el volumen tantito",
        "un poquito más bajo",
        "súbele",
        "sube el volumen unos 10 puntos",
        "bájale 20 puntos al volumen",
        "déjalo casi en silencio pero no del todo",
    ],
    "ABSTAIN__negated_command": [
        "no vayas a subir el volumen",
        "no le cambies el volumen a nada",
        "don't mute anything",
        "no toques el audio por ahora",
        "no me crees ninguna nota todavía",
        "no revises la gpu aún",
    ],
    "ABSTAIN__microphone": [
        "silencia mi micrófono",
        "mute my mic in the call",
        "el micrófono no se escucha",
        "sube la ganancia del micro",
        "mi mic está muteado?",
    ],
    "ABSTAIN__ui_button_report": [
        "en discord apreté el botón de silenciar",
        "le di al mute en la llamada de zoom",
        "me silenciaron en el server",
        "the mute button in teams is grayed out",
        "toqué silenciar sin querer en la reunión",
    ],
    "ABSTAIN__hardware_knowledge": [
        "qué gpu me recomiendas comprar",
        "cuál es mejor la 4060 o la 3070",
        "how much vram does a 4090 have",
        "qué es la vram exactamente",
        "cuánta ram necesita un juego moderno",
        "which cpu is better for gaming",
        "qué es una gpu y para qué sirve",
        "cómo funciona una tarjeta gráfica",
        "explícame qué hace el procesador",
        "conviene comprar gpu propia o usar la nube?",
        "what is a gpu exactly",
    ],
    "ABSTAIN__prices_or_web": [
        "busca el precio de la rtx 4060 en internet",
        "cuánto sale una tarjeta gráfica nueva",
        "search for gpu prices online",
        "cotízame un notebook con buena batería",
        "precios actuales de tarjetas gráficas",
        "cuánto están saliendo las gpu hoy",
    ],
    "ABSTAIN__composition_multistep": [
        "crea una nota con la lista del súper y ponme un recordatorio para mañana",
        "revisa la gpu mientras corre el entrenamiento",
        "abre el bloc de notas escribe un poema y guárdalo",
        "baja el volumen y pon música tranquila",
        "chequea la ram y si está llena cierra chrome",
        "mute the sound and then play a movie",
        "verifica la vram mientras el modelo responde",
        "verifica la gpu mientras el asistente responde un prompt",
        "prueba un prompt largo y mira cómo va la gpu mientras tanto",
        "lanza el entrenamiento y avísame cuánta gpu usa",
    ],
    "ABSTAIN__process_attribution": [
        "qué está usando la vram ahora",
        "qué proceso me come tanta ram",
        "why is my gpu at 100 percent, what app is doing that",
        "qué programa está gastando la batería",
        "hay algo más usando la gpu ahora?",
        "quién está ocupando la vram, es normal eso?",
        "cuánta vram usa solamente esta aplicación",
        "qué procesos están usando la tarjeta gráfica",
    ],
    "ABSTAIN__causal_diagnosis": [
        "por qué mi gpu no se está usando",
        "why is my pc so slow lately",
        "por qué se traba el equipo cuando juego",
        "por qué la ram se llena sola",
    ],
    "ABSTAIN__temperature": [
        "a qué temperatura está la gpu",
        "gpu temp right now",
        "está muy caliente el procesador?",
        "temperatura del sistema",
    ],
    "ABSTAIN__conversation_general": [
        "hola cómo estás",
        "qué puedes hacer por mí",
        "cuéntame un chiste",
        "gracias baxy, muy amable",
        "what do you think about artificial intelligence",
        "explícame qué es docker en simple",
        "ayúdame a redactar un mail para mi jefe",
        "buenos días, todo bien?",
        "quién te creó",
        "tell me something interesting",
    ],
    "ABSTAIN__file_operations": [
        "renombra nota.txt a final.txt",
        "lee el archivo config.json",
        "convierte el documento a mayúsculas en un archivo nuevo",
        "borra los archivos temporales de descargas",
        "copia el pdf al escritorio",
        "abre la carpeta de proyectos",
    ],
    "ABSTAIN__reminders_calendar": [
        "ponme un recordatorio para mañana a las 9",
        "remind me to call mom tonight",
        "agéndame una reunión el viernes a las 3",
        "avísame en media hora",
        "pon una alarma a las 7",
    ],
    "ABSTAIN__other_apps": [
        "abre chrome",
        "cierra spotify",
        "instala visual studio code",
        "open the browser and go to youtube",
        "lanza el juego",
    ],
    "ABSTAIN__statement_no_request": [
        "mi color favorito es el verde",
        "tengo 25 años",
        "la gpu es una 3060 según el vendedor",
        "i usually work from home on fridays",
        "el volumen quedó bien así",
        "ya silencié el audio yo mismo",
        "listo, la gpu dejó de usarse",
        "le puse mute a la tele recién",
        "dejé el volumen bajo antes de salir",
    ],
    "ABSTAIN__tech_work_talk": [
        "el test de integración falla con timeout otra vez",
        "cómo hago un loop en python",
        "el build tarda 11 segundos, se puede mejorar?",
        "hay que refactorizar el parser antes del release",
        "la memoria del proceso se fuga en el worker",
        "corre el benchmark de nuevo con batch 8",
    ],
    "ABSTAIN__document_noise": [
        "**`memoria.json` con solo 3 items** — feature usada poco en el corpus",
        "summarize_verifiers([]) returns empty string cuando no hay info",
        "## Sección 4: resultados del harness de gpu",
        "- [ ] revisar el volumen de datos del ledger antes del corte",
        "línea 42: assert store.notes.count == 512",
        "fig 3 muestra la curva de batería del benchmark",
    ],
}

ALL_POOLS: dict[str, list[str]] = {**POSITIVE_POOLS, **ABSTAIN_POOLS}
